services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

        
    App\Service\Search\SearchEmployeesService:
        arguments:
            $queryRebuilder: '@App\Service\Search\SearchQueryBuilder'
        autowire: true

    App\Service\Search\SearchContractsService:
        arguments:
            $queryRebuilder: '@App\Service\Search\SearchQueryBuilder'
        autowire: true

    App\Service\Search\SearchQueryBuilder:
        calls:
            - [setLogger, ['@logger']]